config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :description)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(params[:cocktail_id])
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class='banner'>
  <h1>Tonight Jacqueline</h1>
  <div class="add-cocktail">
    <%= link_to new_cocktail_path do %>
      <i class="fas fa-plus"></i>
      <i class="fas fa-cocktail"></i>
    <% end %>
  </div>
  <p>
    <span id="banner-typed-text"></span>
  </p>
</div>

<div class="cocktail-cards">
  <% @cocktails.each do |cocktail| %>
    <%= link_to cocktail_path(cocktail), class: 'card-hover' do %>
      <% path = cocktail.photo.attached? ? cocktail.photo.service_url : 'https://images.unsplash.com/photo-1527271982979-83fea3eb3582?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=676&q=80' %>
      <div class="cocktail-card" style="background-image: linear-gradient(rgba(243, 188, 201, 0.3), rgba(0, 0, 0, 0.4)), url('<%= path %>'); background-size: cover; background-position: center;">
        <p><%= cocktail.name %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="form-container background-pink">
  <%= link_to root_path do %>
    <i class="fas fa-arrow-alt-circle-left back-btn"></i>
  <% end %>

  <%= simple_form_for(@cocktail) do |f| %>
    <h3>Name Your Poison 😈</h3>
    <%= f.input :name, label: false %>
    <h3>Tell us more... 👀</h3>
    <%= f.input :description, label: false %>
    <%= f.input :photo, as: :file, label:false, class: "submit-blue" %>
    <%= f.submit "Submit Cocktail", class: "btn-blue" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="cocktail-page">
  <div class="side-image">
    <%= link_to root_path do %>
      <i class="fas fa-arrow-alt-circle-left back-btn pink-btn"></i>
    <% end %>
  </div>
  <div class="cocktail">
    <div class="cocktail-details">
      <h1><%= @cocktail.name %></h1>

      <div class="ingredients">
        <div class="cocktail-description-dosage">
          <div class="cocktail-description">
            <h3>Description</h3>
            <p><%= @cocktail.description %></p>
          </div>
          <div class="cocktail-dosage">
            <h3>How to make a <%= @cocktail.name %>...</h3>
            <hr>
            <% @cocktail.doses.each do |dose| %>
              <div class="ingredient-item">
                <p><%= dose.ingredient.name %> - <%= dose.description %></p>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: 'Are you sure you want to delete this?'}  do %>
                  <i class="far fa-trash-alt"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <button class='add-ingredient-btn'>
      <%= link_to "Hmm, something is missing!", new_cocktail_dose_path(@cocktail) %>
    </button>
  </div>
</div>

app/views/doses/new.html.erb
<div class="form-container background-pink">
  <%= link_to cocktail_path(@cocktail) do %>
    <i class="fas fa-arrow-alt-circle-left back-btn"></i>
  <% end %>
  <h3>What ingredients do we need for your <%= @cocktail.name %>? 🍹</h3>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description, label: false  %>
    <%= f.association :ingredient, label: false  %>
    <%= f.submit "Here we go", class: "btn-blue" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Pacifico|Playfair+Display:400,700&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer>
      <p>Made with ❤️ by Tonight Jacqueline</p>
      <div class="icons">
        <i class="fab fa-facebook"></i>
        <i class="fab fa-instagram"></i>
        <i class="fab fa-twitter"></i>
      </div>
    </footer>
  </body>
</html>